<div class="container my-5">
	<h1>New post</h1>

	<form action="/post/store" method="post">
		<div class="form-group">
			<label for="title">Title: </label>
			<input type="text" name="title" id="title" class="form-control">
		</div>

		<div class="form-group">
			<label for="content">Content: </label>
			<input type="text" name="content" id="content" class="form-control">
		</div>

		<a href="/posts" class="btn btn-secondary">Cancel</a>
		<button type="submit" class="btn btn-primary">Save</button>
	</form>
</div><!-- container -->