<div class="container my-5">
	<h1><?= $this->getPageTitle(); ?></h1>

	<form action="/post/<?= $this->view->post->id ?>/update" method="post">
		<div class="form-group">
			<label for="title">Title: </label>
			<input type="text" name="title" id="title" class="form-control" value="<?= isset($this->view->inputs['title']) ? $this->view->inputs['title'] : $this->view->post->title  ?>">
			<?php 
				if(isset($this->view->errors['title'])): 
			?>
				<span class="help-block"><?= $this->view->errors['title'] ?></span>
			<?php endif; ?>
		</div>

		<div class="form-group">
			<label for="content">Content: </label>
			<input type="text" name="content" id="content" class="form-control" value="<?=  isset($this->view->inputs['content']) ? $this->view->inputs['content'] : $this->view->post->content ?>">
			<?php 
				if(isset($this->view->errors['content'])): 
			?>
				<span class="help-block"><?= $this->view->errors['content'] ?></span>
			<?php endif; ?>
		</div>

		<a href="/posts" class="btn btn-secondary">Cancel</a>
		<button type="submit" class="btn btn-primary">Save</button>
	</form>
</div><!-- container -->