<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Page Not Found</title>
    <link href="/assets/css/style.css" rel="stylesheet">
</head>
<body>

<div class="container">
    <div class="row">
        <div class="my-3 box-erro">
            <h1>Page not found</h1>
            <p>Sorry, the page you are looking for could not be found.</p>
        </div><!-- box-erro -->
    </div>
</div>

<script src="/assets/js/jquery.min.js"></script>
<script src="/assets/js/bootstrap.min.js"></script>
</body>
</html>